DROP TABLE Users_Events CASCADE CONSTRAINTS;
DROP TABLE Participants;
DROP TABLE Albums CASCADE CONSTRAINTS;
DROP TABLE Photos CASCADE CONSTRAINTS;
DROP TABLE Tags;
DROP SEQUENCE album_id_seq;
DROP SEQUENCE user_id_seq;
DROP SEQUENCE photo_id_seq;
-- Question on CASCADE CONSTRAINTS